### ISSUE TITLE
Begin using Cicle CI

### ISSUE THREAD

**Issue by FionaDL** [fastruby/dash#1]
~~Begin using Travis CI~~
Set up Circle CI with the right environment variables.

**Comment by etagwerker** [comment]
@FionaDL I think it is okay if we use Circle CI for this OSS project. I tried to set it up using the new repository but I think I set up the wrong API key. Could you look into this?  https://app.circleci.com/pipelines/github/fastruby/dash/1/workflows/4bd7cb10-2973-4cd9-94b0-40d9926f9032/jobs/2

**Comment by FionaDL** [comment]
@etagwerker @bronzdoc I'm happy to set up for Circle CI, I think the only reason we initially discussed Travis CI was that it seemed to be easier to integrate with Codecov and adding badges? I will work on the adding the correct ENV variables.

**Comment by FionaDL** [comment]
@etagwerker @bronzdoc the build is passing now.

**Comment by bronzdoc** [comment]
Thanks @FionaDL, closing since this is already setup
