### ISSUE TITLE
Seeing Pull Requests or Issues that you have opened. 

### ISSUE THREAD

**Issue by FionaDL** [fastruby/dash#16]
It would be great to have a section that shows the Pr's and Issues that you have opened that are still open so that you can keep track of the progress being made in them.

**Comment by etagwerker** [comment]
It is not quite a section, but more of a new column in the table. 😸 

![Screen Shot 2020-12-01 at 4 06 06 PM](https://user-images.githubusercontent.com/17584/100797532-48b63380-33f0-11eb-929e-478d484b952c.png)
