### ISSUE TITLE
Blank slate should show a call to action instead of an empty header

### ISSUE THREAD

**Issue by etagwerker** [fastruby/dash#18]
I just solved all the pull requests I had in my queue 🎉 and then I ended up with this screen: 

![Screen Shot 2020-06-06 at 8 28 19 PM](https://user-images.githubusercontent.com/17584/83957243-6dac5e00-a834-11ea-9cab-a6c71f0f8a2b.png)

I think it would be best if we had different content in that section. Maybe it can have a call to action to sync my pull requests?

**Comment by cleicar** [comment]
I'll work on this issue next.

**Comment by etagwerker** [comment]
@cleicar Do you have an ETA for this improvement? Could you please post it here? 

Thanks!

**Comment by cleicar** [comment]
@etagwerker this was already addressed on PR #45 

We just forgot to close this issue :)
