### ISSUE TITLE
[BUG] Links are not opening in the project's GitHub page

### ISSUE THREAD

**Issue by etagwerker** [fastruby/dash#22]
**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

`gh-pages` branch. 

**Expected behavior:**

External links in the page https://fastruby.github.io/dash/ should open in a new window or tab.

**Actual behavior:**

External links in the page https://fastruby.github.io/dash/ don't open in a new window or tab.

**Steps to reproduce:**

How do I achieve this behavior? Use the following format to provide a step-by-step guide:

1. Go https://fastruby.github.io/dash
2. Try clicking any of the links in the content section (e.g. Code of Conduct) 
3. Nothing will happen 😢 

**Context and environment:**

![Screen Shot 2020-06-12 at 2 48 55 PM](https://user-images.githubusercontent.com/17584/84536606-34547200-acbc-11ea-85a2-e5c980654c7c.png)

![Screen Shot 2020-06-12 at 2 51 24 PM](https://user-images.githubusercontent.com/17584/84536607-34ed0880-acbc-11ea-9013-061a44d9bcb2.png)

**I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)**

This issue is probably related to this JS code: https://github.com/fastruby/dash/blob/gh-pages/static/styleguide.js#L7 -- .cc @FionaDL @nykka

**Comment by arielj** [comment]
It's probably because of this other js event listener https://github.com/fastruby/dash/blob/gh-pages/static/styleguide.js#L48 (this was used on the styleguide's page but shouldn't be used here)

**Comment by etagwerker** [comment]
@arielj Good point. I know it is a reference to `preventDefault`, I'm not sure which one it is. That's why I cc'ed more people. 👍

**Comment by etagwerker** [comment]
Closed by #23.
