### ISSUE TITLE
Remove locked Ruby version from Gemfile

### ISSUE THREAD

**Issue by sebastian-palma** [fastruby/dash#29]
I just cloned the repo to give it a look and run `bundle` to get the dependencies and had this error _"Your Ruby version is 2.7.1, but your Gemfile specified 2.6.6"_.

Anyway it can just be solved by commenting that line, but I don't know if it's necessary to have that in the Gemfile, or if there are Ruby version constraints in the project.

https://github.com/fastruby/dash/blob/11dbd9a1f6735dda611ebbecbc19fc898bda83d4/Gemfile#L4

**Comment by arielj** [comment]
Hi @sebastian-palma, thanks for taking the time to try Dash.

Even though it runs with Ruby 2.7, we are not 100% sure if all gems we use are prepared to work with that Ruby version.  There are some warnings and deprecation warnings with Ruby 2.7 and we currently run Ruby 2.6.6 in production. 

Also, it's common for Heroku and RVM to use that line from the Gemfile to set the Ruby version for development and deploys.

You can of course use it without that restriction, just take in mind we don't run that Ruby version in production so we are not sure if there's any bug related to that. We may eventually remove that restriction when we are sure it's working properly.

**Comment by sebastian-palma** [comment]
I understand @arielj, maybe it'd be good to have the required Ruby version in the README to avoid having people asking the same 😅.

**Comment by FionaDL** [comment]
@sebastian-palma great idea, we will add it.
