### ISSUE TITLE
Sync Pivotal Stories task.

### ISSUE THREAD

**Issue by FionaDL** [fastruby/dash#3]
As a user, I would like to see my pivotal stories with their updated status without having to enqueue a sync job.

**Why**
I want to see an updated list of pivotal stories every time I load the page
So that I don't have to synchronously sync my pivotal stories

**Scenario:** 
Given that pivotal stories are constantly being updated
When I sign back in and open my dashboard
Then I should see a list of pivotal stories with their up to date status

**Notes:**
There should be a regular cron job (Heroku scheduler) that runs a rake task which does this:

Find all open pivotal stories in our system database
Call the Pivotal Tracker API to find the pivotal stories updated status and list of assignees
Update our database accordingly

**Comment by etagwerker** [comment]
@FionaDL quick question about this. Do we have a scheduled job running in Heroku? If so, how often does it run?

**Comment by cleicar** [comment]
@etagwerker yes, we do. Right now we only have the jobs for Pull Requests and Issues

<img width="1284" alt="Screen Shot 2021-01-29 at 09 48 43" src="https://user-images.githubusercontent.com/11785031/106277031-2fc2d680-6217-11eb-930c-f882e7430781.png">
