### ISSUE TITLE
[BUG] Deleted pivotal stories are not deleted from Dash

### ISSUE THREAD

**Issue by arielj** [fastruby/dash#34]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

Master branch

**Expected behavior:**

When a story gets deleted, it should also disappear from my Dash dashboard.

**Actual behavior:**

When a story is deleted, it's there in the dashboard and there's no way to make it go away.

**Steps to reproduce:**

1. Step 1: delete a story that you see in your dashboard
2. Step 2: after syncing, the story is still there

**I will abide by the [code of conduct] (https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)**

I'm not sure if we need to handle the story being deleted or if we should give the user an option to remove stories manually.

**Comment by cleicar** [comment]
@arielj I'll start this story.

**Comment by bronzdoc** [comment]
Closed by https://github.com/fastruby/dash/pull/46
