### ISSUE TITLE
[REQUEST] See the pull request's owner

### ISSUE THREAD

**Issue by cleicar** [fastruby/dash#47]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and didn't find this feature
- [x] I checked to make sure that this feature has not already been requested

**Branch/Commit:**

`main`

**Describe the feature:**

Please include a detailed description of the feature you are requesting and any detail on it’s expected behavior.

> **As a User**
> **I would like to see the PR owner**
> **So that I can check if the PR was created by me or just assigned to review**
 
**Problem:**

Today I have to go inside each PR to remember the ones I'm waiting for a request or that are waiting for me to review.
 
**I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)**

**Comment by arielj** [comment]
I understand this PR by @FionaDL would fix this problem, right? https://github.com/fastruby/dash/pull/42

Currently only PRs where you are a reviewer or an assignee are showing on dash, but not the ones you created (and I think you can't be tagged in your own PRs)

**Comment by etagwerker** [comment]
You can now see the owner in the table: 

![Screen Shot 2020-12-01 at 4 06 06 PM](https://user-images.githubusercontent.com/17584/100796760-25d74f80-33ef-11eb-887b-4c7445daad43.png)
