### ISSUE TITLE
[BUG] Todos show duplicate PRs when the user is both the owner and assignee

### ISSUE THREAD

**Issue by arielj** [fastruby/dash#59]
**Branch/Commit:**

Main

**Expected behavior:**

Each PR should be shown only once if I'm the owner AND I'm the user that needs to do some action.

**Actual behavior:**

Currently, we are concatenating all different queries and that can lead to having the same PR as assignee and owner showing up at the same time.

**Steps to reproduce:**

Create a PR and wait for it to require a change on your side (like having requested changes)

**Screenshots and Videos**

![Screen Shot 2020-12-14 at 10 14 15 AM](https://user-images.githubusercontent.com/188464/102085302-31fedc00-3df5-11eb-9ecf-67c9ce4efbaf.png)

**I will abide by the [code of conduct] (https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)**

**Comment by cleicar** [comment]
Solved in #62
