### ISSUE TITLE
Sidebar links to dash.ombulabs.com instead of fastruby.github.io/dash/

### ISSUE THREAD

**Issue by arielj** [fastruby/dash#68]
**Branch/Commit:**

Main branch.

**Expected behavior:**

As a user trying to learn about Dash, I want to see a link to the [GitHub Page](https://fastruby.github.io/dash/) for Dash in the sidebar's About section.

**Actual behavior:**

In the sidebar, we have a link to our private app's url: https://dash.ombulabs.com

![image](https://user-images.githubusercontent.com/188464/107227066-b63a9d80-69f9-11eb-95d5-b58c30dd6ac8.png)

**I will abide by the [code of conduct] (https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)**

**Comment by bronzdoc** [comment]
Fixed, closing
