### ISSUE TITLE
[BUG] Outdated labels?

### ISSUE THREAD

**Issue by arielj** [fastruby/dash#69]
We currently have the labels for the hacktoberfest2020, not sure if we want to remove them.

![image](https://user-images.githubusercontent.com/188464/107227276-f69a1b80-69f9-11eb-81fd-1e480b289a6a.png)

**Comment by bronzdoc** [comment]
I think we could remove the `hacktoberfest2020` one @arielj 👍

**Comment by bronzdoc** [comment]
I think is gone now so this can be closed
